### ISSUE TITLE
Point multiplication by negative factor is not correct

### ISSUE THREAD

**Issue by naumazeredo** [AntonKueltz/fastecdsa#10]
Simple verification with negative factor fails like shown:

```
#!/usr/bin/env python

from fastecdsa.curve import P256
from fastecdsa.point import Point

a = -1 * P256.G
b = (-1 % P256.q) * P256.G

assert(a == b)
```

As stated in [StackExchange](https://crypto.stackexchange.com/a/31066), the identity ```xP = (x+q)P``` should hold even for negative values.

I think that if all multiplications should be done modulus curve's ```q``` (but I don't know much about EC, so the fix could be broader).

**Comment by AntonKueltz** [comment]
Thanks for catching that, you're correct that negatives should simply by multiplied by the element in Zq that they are congruent to. Fixed in commit  e38578e, will be in version 1.4.3.

```python
In [1]: from fastecdsa.curve import P256

In [2]: from fastecdsa.point import Point

In [3]: a = -1 * P256.G

In [4]: b = (-1 % P256.q) * P256.G

In [5]: assert(a == b)

In [6]:
```
