### ISSUE TITLE
Issues Installing Ubuntu 18

### ISSUE THREAD

**Issue by Swaggadan** [AntonKueltz/fastecdsa#29]
I have Ubuntu 18 .1. I installed python 3.7.2. I have tried to install fastecdsa1.6.5 but I get this [error](https://pastebin.com/05Rby9Wd). 

`building 'fastecdsa.curvemath' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/ -I/usr/local/include/python3.7m -c src/curveMath.c -o build/temp.linux-x86_64-3.7/src/curveMath.o -O2
In file included from src/curveMath.c:1:0:
src/curveMath.h:6:10: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
          ^~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
`

**Comment by AntonKueltz** [comment]
Did you install the additional required packages listed in the Installation part of the README? Give the following a shot -

```bash
sudo apt install python-dev libgmp3-dev
```

If that doesn't work let me know.

**Comment by Swaggadan** [comment]
It worked with your suggest. My mistake. I was following a guide with this as a program to use but that guide didn't install python dev and libgmp3 dev. Thank you kind sir.

**Comment by AntonKueltz** [comment]
No problem, happy to help :)

**Comment by masiev** [comment]
`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g60nkxit/fastecdsa-any/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2fj7a4_4-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-g60nkxit/fastecdsa-any/`
