### ISSUE TITLE
name unicode not defined

### ISSUE THREAD

**Issue by oditorium** [AntonKueltz/fastecdsa#36]
![Screen Shot 2019-04-27 at 17 25 50](https://user-images.githubusercontent.com/8403420/56852324-d7f48e80-6911-11e9-8dc9-29b15d88018a.png)

**Comment by AntonKueltz** [comment]
One of the joys of writing a package that works for python2 and python3 is handling the different string / binary types... fixed in 41a9c85e77dd59cbf0a22dee252e10ba55ecfe25.

**Comment by oditorium** [comment]
yeah; just drop P2 support and/or have people pay you for it; at this stage everyone using P2 does it because they can't be bothered to port their legacy code base to P3, so they might as well pay for the privilege of having up to date libraries...

**Comment by AntonKueltz** [comment]
I'll support python2 until it's EOL, only a couple more months, after that releases will be only python3 compatible.
