### ISSUE TITLE
Compressed verifying keys?

### ISSUE THREAD

**Issue by thejohnfreeman** [AntonKueltz/fastecdsa#47]
There seems to be a popular [compression scheme](https://bitcoin.stackexchange.com/questions/69315/how-are-compressed-pubkeys-generated) for ECDSA verifying (public) keys. Does this library support them? Something like [this](https://github.com/warner/python-ecdsa/blob/master/src/ecdsa/keys.py#L217-L236) in `ecdsa`?

**Comment by AntonKueltz** [comment]
I'm not sure what you mean by verifying? The compression scheme you indicate just compresses the point down from x/y coordinates to just x coordinate and a byte indicating the value of y mod 2. That scheme is easy enough to implement and can be added to the backlog of work.

**Comment by thejohnfreeman** [comment]
Oh sorry, I meant "verifying key", as in "a key for verifying a signature", or "public key". I got mixed up, and forgot this library doesn't use the "verifying key" terminology that some others do. I'll rephrase:

> There seems to be a popular compression scheme for ECDSA public keys.

I'm just asking for functions to compress and expand the public key according to this scheme. Happy to see it added to the backlog.

**Comment by AntonKueltz** [comment]
Ah gotcha, shouldn't be too hard to do but hasn't been any requests for it till now. Will add it to the TODO list.

**Comment by AntonKueltz** [comment]
@thejohnfreeman getting around to doing this, do you know if there’s an official spec / rfc for this encoding? If not I propose we just implement this as a bytes to Point function in the keys file.

**Comment by AntonKueltz** [comment]
@thejohnfreeman  sorry for the delay here, I missed that the SEC1 encoder already does this when I first looked at this request. You can use `SEC1Encoder.decode_public_key(bytes, curve)` to do this, the [docs for the method](https://fastecdsa.readthedocs.io/en/latest/fastecdsa.html#fastecdsa.encoding.sec1.SEC1Encoder) have some additional details as well.

**Comment by AntonKueltz** [comment]
Closing this out, feel free to re-open if the above does not address your needs. 👍
