### ISSUE TITLE
encrypting with EC?

### ISSUE THREAD

**Issue by Thetoxicarcade** [AntonKueltz/fastecdsa#5]
Is it possible to encrypt with EC in python?

**Comment by AntonKueltz** [comment]
It is possible insofar as there are schemes that support encryption using EC, for example [Elliptic Curve Integrated Encryption Scheme](https://en.m.wikipedia.org/wiki/Integrated_Encryption_Scheme). This package however only aims to support digital signatures and basic curve operations like point addition and multiplication. I'm unaware of a Python package that provides a ECIES implementation.

**Comment by AntonKueltz** [comment]
(Closing this as this package is for digital signatures, not encryption.)
