### ISSUE TITLE
Type checks when calculating with point at infinity

### ISSUE THREAD

**Issue by jannikluhn** [AntonKueltz/fastecdsa#50]
At the moment, there are cases in which calculating with the point at infinity gives unexpected results and others in which an `AttributeError` is raised:

- `Point.IDENTITY_ELEMENT + 2` gives `2`
- `Point.IDENTITY_ELEMENT - 2` raises an `AttributeError`
- `Point.IDENTITY_ELEMENT * 1.5` raises an `AttributeError`

In all of these cases I would expect an `TypeError`.

**Comment by AntonKueltz** [comment]
Good catch. Fixed in 3fef4b1753fa23afb7d7008897aac7b9bb995479, released in v2.1.0.
