### ISSUE TITLE
Great library — keep it up

### ISSUE THREAD

**Issue by paulmillr** [AntonKueltz/fastecdsa#51]
Hi @AntonKueltz 

This is not a bug report. I was wandering around GitHub looking for ECC libraries to learn it and [implement by myself](/paulmillr/noble-secp256k1). Almost every lib out there is shitty for learning. They have tons of dependencies, tons of unreadable "optimized" code.

Thanks for such a great tool! fastecdsa is one of the best in this regard. Please keep it up. In particular, Python is very helpful due to built-in bigint support.

**Comment by AntonKueltz** [comment]
Thanks for the kind words, glad you’re finding the project useful!
