### ISSUE TITLE
Point to non-point equality

### ISSUE THREAD

**Issue by jannikluhn** [AntonKueltz/fastecdsa#53]
Checking equality of a curve point with something which is not a curve point [raises a type error](https://github.com/AntonKueltz/fastecdsa/blob/master/fastecdsa/point.py#L53). Instead, I think it should return `False` which is, at least in my experience, the standard convention. (e.g. `5 == "5"`, `None == object()`, `{} == []`).

**Comment by AntonKueltz** [comment]
It is a bit unconventional compared to the builtin types and their comparisons, but I think it provides a clearer picture to the user as to what is going on. The cases being -
* Two points have the same x and y coordinates on the same curve -> `True` as the points are equal
* Two points are not on the same curve or having differing x and y coordinates -> `False` as the points are not equal
* A point is compared to something that isn't a point -> `TypeError` this comparison does not make sense / cannot be made, and distinguishes the comparison from two points being compared but not being equal

If there's a use case where this is an issue I'm happy to reconsider, but my initial thoughts here are that this provides stronger and clearer indications of what's going on than just returning `False` and not failing / throwing an exception.

**Comment by jannikluhn** [comment]
Fair enough, sounds reasonable! I just stumbled over this by accident and was a little bit surprised by the behavior, so I wanted to point it out.
