### ISSUE TITLE
Importing a public key (originally a byte array) from a ATECC508A cryptochip

### ISSUE THREAD

**Issue by bshambaugh** [AntonKueltz/fastecdsa#57]
This involves importing a public key from the cryptographic chip ATECC508A into the library. I found I had a public key that was generated using the p-256 according to the chip documentation, yet the fastecdsa library tells me that the point is not on the curve.

I created a gist to describe my procedure:
https://gist.github.com/bshambaugh/6f0fe5a63f96b0e0a95b404cc103e9c4

As well as my broader (newbie) exploration:
https://raptorlicious.blogspot.com/2020/07/bringing-together-last-3-cryptography.html

If this is out of scope, is there a better place for this question? Thanks for your time.

**Comment by bshambaugh** [comment]
I am going to close this issue. I tried a public key from stack-overflow and it worked. For more information see:
https://gist.github.com/bshambaugh/6f0fe5a63f96b0e0a95b404cc103e9c4

**Comment by AntonKueltz** [comment]
Sorry I’m just now getting a chance to look at this, will double check tomorrow that the original issue isn’t a problem with this library.
