### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by targon** [AntonKueltz/fastecdsa#6]
Some of the functions seem to leak memory. The test program below will continuously eat up more and more memory. 

I suspect the issue is in your use of Py_BuildValue without freeing the char* afterwards. For example, in curvemath_mul, resultX and resultY are allocated but never freed.

```python
#!/usr/bin/env python

import fastecdsa.curvemath, fastecdsa.curve, gc

sx = str(fastecdsa.curve.secp256k1.G[0])
sy = str(fastecdsa.curve.secp256k1.G[1])
sz = str(2**255-1)

while True:
    fastecdsa.curvemath.mul(sx, sy, sz, 'secp256k1')
    gc.collect()
```

**Comment by AntonKueltz** [comment]
Thanks for the info, I suspect this was introduced via the branch the added koblitz curves. I'll take a look and submit a patch within the next day or two.

**Comment by AntonKueltz** [comment]
Issue seems to be coming from the memory management in the binary field logic, in the process of mitigating.

**Comment by targon** [comment]
Attached patch fixes a number of memory leaks. After applying it, I can run curvemath.mul, curvemath.add and _ecdsa.verify in loops without increasing the memory usage.

[memleak.patch.txt](https://github.com/AntonKueltz/fastecdsa/files/761790/memleak.patch.txt)

Can you please check & merge?

**Comment by AntonKueltz** [comment]
Will verify patch tonight and merge, thanks!

**Comment by AntonKueltz** [comment]
Changes merged, thanks again for the patch.

Keep issue open as there is still major memory leakage in the binary curves. To replicate on macOS take the following steps:

* cd into the `src/` folder
* in `test.c` go to the bottom of the file and uncomment all function calls in `main`
* run `$ make` to produce the `ecdsa` binary
* open up Instruments -> Leak Checks and select the `ecdsa` binary as the target
* observe that significant memory leakage is reported

Keeping this issue open until this is resolved.

**Comment by EggPool** [comment]
I gave this a try with current version and secp256k1:
signature checks do not leak anymore, but signing does.

`import gc, os, psutil
from hashlib import sha1

from fastecdsa import ecdsa
from fastecdsa.curve import secp256k1
from fastecdsa.keys import gen_keypair

message = b"Sample message for signature testing"
priv, pub = gen_keypair(secp256k1)

CHECK_SIGN = True
CHECK_VERIFY = False

process = psutil.Process(os.getpid())
r, s = ecdsa.sign(message, priv, hashfunc=sha1, curve=secp256k1)

while True:
    print(process.memory_info().rss)
    if CHECK_SIGN:
        for i in range(1000):
            r, s = ecdsa.sign(message, priv, hashfunc=sha1, curve=secp256k1)
        gc.collect()
    if CHECK_VERIFY:
        for i in range(1000):
            check_sig = ecdsa.verify((r, s), message, pub, curve=secp256k1, hashfunc=sha1)
        gc.collect()`

**Comment by AntonKueltz** [comment]
Verified memory leak. Will need to write some C test code and profile with memory leak tools.
