### ISSUE TITLE
deep learning for fastecdsa 

### ISSUE THREAD

**Issue by mamumi** [AntonKueltz/fastecdsa#66]
Is it possible to adapt fastecdsa to tensorflow and run it with gpu on python?

**Comment by AntonKueltz** [comment]
Hi there,

What would be the use case for this? Elliptic curve cryptography, specifically ECDSA doesn't have many ML / GPU computing applications that I'm aware of.

**Comment by mamumi** [comment]
Written in Python, this library works just like sagemath. I need it to do some tests with the Elliptic Curve Arithmetic GPU. It can be used in an academic research. My current research cyclic-group on elliptic curve. is it possible ?

**Comment by AntonKueltz** [comment]
> Written in Python, this library works just like sagemath.
I'm not sure I agree, sage is a python-like language syntactically, but this package does not aim to implement any of the same interfaces that EC libraries in sage do.

> I need it to do some tests with the Elliptic Curve Arithmetic GPU. It can be used in an academic research. My current research cyclic-group on elliptic curve. is it possible ?
How does deep learning fit into the picture? And why use the GPU for general EC computing? GPUs are good at highly parallel workloads, EC computations are generally not suited for this model.

**Comment by mamumi** [comment]
I need parallel processing power for my cyclic-group trials. tensorflow can negotiate with GPU. Considering Tensorflow framework, I think I can do fast parallel processing. 

```
i = 0
while True:
    i=i++
    S = i*G
    if S.x % 989877687686 == 8794564 and  S.x % 778978987686 == 6874512 :
        savefile (i)

```
