### ISSUE TITLE
Point extend

### ISSUE THREAD

**Issue by hamnaz** [AntonKueltz/fastecdsa#68]
abc
023ef30130654689a64c864d6dd38760481c55fc525e2c6c7084e2d2d3d4d51be9
043ef30130654689a64c864d6dd38760481c55fc525e2c6c7084e2d2d3d4d51be9f7d86b288c09ddb5311f292285168000e43e4b62201bd8de23a391daa8e00ce8

def
036a6e1dc6f203f7fdd97965892301e5fb995a37318c410543835f0edcd3456c49
046a6e1dc6f203f7fdd97965892301e5fb995a37318c410543835f0edcd3456c492a072b9898b93e9eb05f9ad86a97546d83b579bf6efd3482f93baca13784496b

abcdef
0312faae608bd6562562b8f85564664cd1fdcd667f6b24b2b221ef86b9231f4d74
0412faae608bd6562562b8f85564664cd1fdcd667f6b24b2b221ef86b9231f4d74512ee8cd9b34331afd05ccb8d81d1393c150c73ec5695845b731f7e6e0086719

here abc is 1 point, and 2nd point is def
if we can join or merge like abc add to def
where result would be abcdef point
have you study and experiance this
maybe some help here 
http://web.math.princeton.edu/swim/SWIM%202010/Yao-Zhan%20Presentation%20SWIM%202010.pdf

hope you will add this func too

**Comment by hamnaz** [comment]
point 1
point 2
a =1+2 = 3
more advance looking func

point 1
point 2
a =1+2 = 12

**Comment by AntonKueltz** [comment]
What is this function supposed to do?

**Comment by hamnaz** [comment]
as above pubkey abc add(line extend) with pubkey def
and result of pubkey of abcdef

**Comment by hamnaz** [comment]
as add func inside your curve.py, bring
abc+def = 18AB
one new func could be inside
like abc+def = abcdef
like point +point = pp ( line extended) ( not 2p)

**Comment by AntonKueltz** [comment]
You can’t just concatenate coordinates (if that’s the request) on a curve to make new coordinates. I’m not sure what the use case would be but the result would not be a valid curve point.

**Comment by hamnaz** [comment]
if both point are under F, then hope could be valid, and if range goes out, then error will apear, try some fomula's, maybe we reach at Goal

**Comment by AntonKueltz** [comment]
I still don’t think i understand the intent or use is here. Unless you can provide a detailed example of how you expect this to work, along with use cases for why this is needed, I’m going to close this ticket.

**Comment by hamnaz** [comment]
during play with ecc, add, substract, multiply, div, i check all ways working, and suddenly apear in mind, could be point addition like point concatenate 
like as above example of abc is hex and pubkey, add with def is hex and pubkey
if it works, then further calc will help me to research inside results

**Comment by AntonKueltz** [comment]
I don't think there's a reason to include concatenation as part of this library since not a standard ECC operation and doesn't have any practical applications i.e. cryptographic schemes that use it. You should be able to implement this fairly quickly if you want to experiment with key concatenation but I don't see any reason to support it in this codebase.

**Comment by hamnaz** [comment]
you can create separate codebase for beta testing share with me personal or publicly , and let world test and use in different stages, 
no one can predict before , till some idea's come to know in practical,

**Comment by AntonKueltz** [comment]
Feel to free to fork this repo and implement any experiments as you see fit.
