### ISSUE TITLE
tag 2.2.2 unsigned, PyPI upload missing a signature file

### ISSUE THREAD

**Issue by lmartinez-mirror** [AntonKueltz/fastecdsa#77]
Hi, I maintain `fastecdsa` on the AUR for Arch Linux. The package fetches a signature file that verifies the source tarball from PyPI.

However, with version 2.2.2, both the tag and the tarball are missing a signature and/or signature file, respectively. Could you please make an effort to sign your tags or, at the very least, ensure your tarballs have a corresponding signature file on PyPI?

Thanks!

**Comment by AntonKueltz** [comment]
Yes, this was an oversight on my part (switched to a new dev machine and didn’t set up new keys for pypi publishing). The next release will include the corresponding signatures again. Let me know if there’s anything in 2.2.2 that you need that warrants an immediate new release with those files.

**Comment by AntonKueltz** [comment]
Version 2.2.3 ([pypi](https://pypi.org/project/fastecdsa/2.2.3/), [tag](https://github.com/AntonKueltz/fastecdsa/commit/9bf593cd29cc497051b45f7271e95fd019e917bd)) should have the signatures again.
