### ISSUE TITLE
symbol not found in flat namespace '___gmpz_add'

### ISSUE THREAD

**Issue by StasFQ** [AntonKueltz/fastecdsa#89]
I'm trying to use bitcoinlib.But I have this error with fastecdsa
site-packages/fastecdsa/_ecdsa.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '___gmpz_add'

**Comment by AntonKueltz** [comment]
You could give `brew install gmp` a try, looks like an issue with a missing library referenced from the C extension.
