### ISSUE TITLE
unresolved external symbol __gmpz_set

### ISSUE THREAD

**Issue by Pixsy1929** [AntonKueltz/fastecdsa#93]
I did everything , but it's not going to fix , pleas somebody help 
gmp is installed

Creating library build\temp.win-amd64-cpython-312\Release\src\curvemath.cp312-win_amd64.lib and object build\temp.win-amd64-cpython-312\Release\src\curvemath.cp312-win_amd64.exp
      curve.obj : error LNK2001: unresolved external symbol __gmpz_clears
      curve.obj : error LNK2001: unresolved external symbol __gmpz_init_set_str
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_init
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_invert
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_cmp
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_cmp_ui
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_init_set
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_mul_ui
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_set_ui
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_mul
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_sub
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_clear
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_inits
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_get_str
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_tstbit
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_sizeinbase
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_mod
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_add
      curveMath.obj : error LNK2001: unresolved external symbol __gmpz_set
      build\lib.win-amd64-cpython-312\fastecdsa\curvemath.cp312-win_amd64.pyd : fatal error LNK1120: 19 unresolved externals
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120

**Comment by AntonKueltz** [comment]
Windows is not officially supported as installing and linking GMP is not straightforward. I would recommend taking a look at [this issue](https://github.com/AntonKueltz/fastecdsa/issues/11). If your problem persists, please use that issue's thread to continue the discussion.
