### ISSUE TITLE
symbol not found in flat namespace '___gmpz_add' Error in version 2.3.2

### ISSUE THREAD

**Issue by wistoff** [AntonKueltz/fastecdsa#94]
```
from fastecdsa import _ecdsa
ImportError: dlopen(/Users/kjellxvx/opt/anaconda3/envs/myenv/lib/python3.8/site-packages/fastecdsa/_ecdsa.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '___gmpz_add'
```

I get this error on my Silicon Mac... None of the suggested solution in the other issues helped. This error does occur since version 2.3.2, the lastest update. 

Installing the previous version fixes the issue.

pip3 install fastecdsa==2.3.1

**Comment by AntonKueltz** [comment]
Version 2.3.1 was yanked and should not be used because the C extensions were not correctly built. See [the pypi release page](https://pypi.org/project/fastecdsa/#history) for reference. Is GMP installed on your machine (`brew install gmp`)?

**Comment by AntonKueltz** [comment]
Looks like the same issue as [this comment](https://github.com/AntonKueltz/fastecdsa/issues/74#issuecomment-2101026452). Closing this issue, please use the linked issue to discuss further. Also, in the future please provide a full trace and code snippet that raised the error, that helps with root causing. Thanks.
